# Generated by Django 3.2.4 on 2021-06-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('precio', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=models.CASCADE,null=True, blank=True, to='core.componente')),
                ('fabricante', models.ForeignKey(on_delete=models.CASCADE,null=True, blank=True, to='core.fabricante')),
            ],
        ),
    ]
