# Generated by Django 3.2.4 on 2021-06-21 23:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210620_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='id',
            new_name='id_comp',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='id',
            new_name='id_fabr',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Producto.ruta_imagen),
        ),
    ]
